#!/bin/sh

pgrep -x sxhkd > /dev/null || sxhkd &

feh --bg-scale --randomize ~/Documents/wallpapers/* &
polybar & 
xsetroot -cursor_name left_ptr
xset r rate 200 50

bspc monitor -d "I" "II" "III" "IV" "V"

bspc config border_width 4
bspc config window_gap 10

bspc config split_ratio 0.5
bspc config focus_follows_pointer true

