#!/bin/sh

pgrep -x sxhkd > /dev/null || sxhkd &

feh --bg-scale --randomize ~/Documents/wallpapers/* &
tint2 &

xsetroot -cursor_name left_ptr
xset s off
xset r rate 200 50

bspc monitor -d 1 2 3 4 5

bspc config border_width 4
bspc config window_gap 10

bspc config split_ratio 0.5
bspc config focus_follows_pointer true

